plugins {
    id 'java-library'
    id 'io.freefair.lombok' version "9.2.0"
}

group = 'guru.qa'
version = '1.0-SNAPSHOT'



repositories {
    mavenCentral()
}

dependencies {
    testImplementation(
            'org.junit.jupiter:junit-jupiter:5.10.1',
            'org.slf4j:slf4j-simple:2.0.17',
            'net.datafaker:datafaker:2.5.4',
            'io.rest-assured:rest-assured:6.0.0',
            'io.rest-assured:json-schema-validator:6.0.0',
            'org.assertj:assertj-core:3.25.3'
    )
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}



tasks.withType(Test) {
    useJUnitPlatform()
    systemProperties(System.getProperties())

    testLogging {
        lifecycle {
            events "started", "skipped", "failed", "standard_error", "standard_out"
            exceptionFormat "short"
        }
    }
}